### ISSUE TITLE
Device discovery from within docker container

### ISSUE THREAD

**Issue by endotronic** [fondberg/spotcast#131]
Thanks so much for all the hard work here! This, combined with the custom card, is really useful. There's one issue I'm having, though, that I hope someone can advise on.

I run Home Assistant in Docker, and though I have the container using the host network (network_mode: host), this plugin is unable to find other Spotify Connect devices. I understand that Spotify uses zerconf (Avahi, Bounjour, etc) for this, but I am not sure how to get discovery to work from within a docker container. This may likely not be a problem not limited to this particular plugin, but alas, maybe it is.

My test setup:
Spotify for Windows (also tried macOS) on 192.168.1.0/24
Linux server running docker on same 192.168.1.0/24 subnet
Home Assistant in docker container using host network
librespot in docker container using host network

Results:
When any Spotify device is playing, it is available everywhere. When no device is playing, Spotify for Windows/macOS can see the librespot device. Home Assistant via spotcast cannot see any device.

I don't know enough about how docker networking handles TCP multicast to have any idea if the container should be able to perform service discovery. I passed `/var/run/dbus` through to the HA container after seeing this suggested for other zeroconf situations, but this made no change. I'm thinking that if this is actually part of the solution, there must be some client needed on the host to make this work, but I am not sure what that is.

Any thoughts for how to enable discovery in a docker container? Thanks in advance! Also if there are any logs to collect, let me know where to find them. I am not sure where to find them right now.

**Comment by fondberg** [comment]
Hi! spotcast doesn't actually itself contain any discovery other than a HTTP Rest call to get connected devices from the spotify web api. 
If you don't see any chromecast devices you should ask in HA support forums as this uses zeroconf. 
If you on the other hand don't see any spotify connected devices it is probably because either you use the wrong account or they are not started.

**Comment by sploders101** [comment]
One solution that may help is specifying your spotify login with `-u` and `-p`. I think it would be awesome if spotcast were able to do this, but unfortunately it won't be able to find it until this changes. However, by specifying your login, you advertise it to Spotify as an *app*, which **will** show up in the list, because it should be returned in the query fondberg mentioned. I haven't tested any of this though, but it's worth a shot.

**Comment by endotronic** [comment]
Thank you! I'll see if I can make that work for me. I'm afraid I haven't had much time to work on it lately.

I'll close this since fondberg explained that this isn't an issue with spotcast.
