### ISSUE TITLE
Component sends command but nothing happens

### ISSUE THREAD

**Issue by almostserious** [fondberg/spotcast#15]
After sometime, the component seems to run in some sort of timeout. While the component sends the request without throwing an error, the cast will not react. After a restart of HA this is fixed.

**Comment by fondberg** [comment]
That is weird. I mean it doesn't do anything or store any data. Do you get
any errors in the log?

Den lör 25 maj 2019 13:19almostserious <notifications@github.com> skrev:

**Comment by almostserious** [comment]
No errors. Even the cast group works. The Speakers make this initial ding sound. But Spotify simply isnt playing anything and also isnt showing anything as playing.

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by fondberg** [comment]
Can you add debug to the component logging and see where it fails? I suspect it is the matching of chromecast device id to spotify device id that fails.

**Comment by almostserious** [comment]
So.. different behaviour depending if i send the play command to a group or a single speaker. Sending to a group will result in no error message, and the chromecast group to become active (making the "ding" sound) but nothing will be played. Debug showing nothing

Sending to a single speaker will result in an error and nothing played. Debug:

```
2019-05-28 07:32:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139702458084824] 'SpotifyController' object has no attribute 'device'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1141, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1165, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 157, in start_casting
    if device['id'] == sp.device:
AttributeError: 'SpotifyController' object has no attribute 'device'
```

**Comment by fondberg** [comment]
I got this as well on my RPI and I added some debug and it seems it works now. 
Can you try with this https://github.com/fondberg/spotcast/pull/17?

**Comment by fondberg** [comment]
After a lot of tests I think the problem is in pychromecast and possibly in the chromecast state. After a lot of testing it is not possible anymore to get the device from the SpotifyController. Doing a playback in the Spotify webplayer in chrome and restarting HASS seems to make it work again. 
I believe the issue is with the return here https://github.com/balloob/pychromecast/blob/010ce59742884887a6f7bae925cb4c2a59bdada0/pychromecast/controllers/spotify.py#L51 does not contain a device id.

**Comment by soldag** [comment]
This is probably caused by an older version of pychromecast. I had the same issue, which I could fix by installing the latest version 3.2.2 manually.

The `cast` component uses 3.2.1 currently and I am not sure how HomeAssistant handles conflicting versions of dependencies. It seems like it reinstalls the old version at some time.  Anyway, I already created a PR for bumping the version to 3.2.2: https://github.com/home-assistant/home-assistant/pull/24234.

**Comment by fondberg** [comment]
I didn't think of this. Great find!

**Comment by almostserious** [comment]
Was this move to 3.2.2 merged in 0.94? For me the Spotcast component currently does not work at all anymore. Not even after a direct restart. Same issue as before: no attribute 'device'

**Comment by soldag** [comment]
Nope, it's not yet included in 0.94. You could install home-assistant directly from github to give it a try or wait for the next release.

**Comment by fondberg** [comment]
You can install an older version which specified 3.2
1 in its manifest but you would lose  the new features of the latest release. Let me know if you need help with how to pull that from git as I haven't tagged the versions

**Comment by fondberg** [comment]
Wait for HA to release pychromecast 3.2.2
