### ISSUE TITLE
Error: Timeout when waiting for status response from Spotify app

### ISSUE THREAD

**Issue by RafhaanShah** [fondberg/spotcast#151]
Hey thanks for the great component, but was just having a small issue I can't seem to figure out. 

The service call does not seem to like one of my Chromecast enabled devices, specifically my [Beoplay M5 Speaker](https://www.bang-olufsen.com/en/speakers/beoplay-m5). I keep getting an error when trying to use Spotcast with this device. (Works fine with my Google Home Mini though)

The speaker does have 'Spotify Connect', and I've tried after disconnecting it from Spotify Connect also.

I was just trying with no additional options, but I have tried various combinations of `force_playback`, `entity_id`, `device_name`, using a playlist `uri` etc.

I've attached the logs, let me know if there's any other way I can help you out.

Home Assistant Version: 2020.12.7
Spotcast Version: v3.4.6

```
today at 10:53 PM  2020-12-18 22:53:13 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:38d8a8911db53276352061f316d61035): entity_id=media_player.speaker, random_song=False, shuffle=False, offset=0, force_playback=False, repeat=off, start_volume=101>
today at 10:53 PM  Traceback (most recent call last):
today at 10:53 PM    File "/usr/src/homeassistant/homeassistant/core.py", line 1461, in catch_exceptions
today at 10:53 PM      await coro_or_task
today at 10:53 PM    File "/usr/src/homeassistant/homeassistant/core.py", line 1484, in _execute_service
today at 10:53 PM      await self._hass.async_add_executor_job(handler.job.target, service_call)
today at 10:53 PM    File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
today at 10:53 PM      result = self.fn(*self.args, **self.kwargs)
today at 10:53 PM    File "/config/custom_components/spotcast/__init__.py", line 295, in start_casting
today at 10:53 PM      spotify_cast_device.startSpotifyController(access_token, expires)
today at 10:53 PM    File "/config/custom_components/spotcast/__init__.py", line 458, in startSpotifyController
today at 10:53 PM      sp.launch_app()
today at 10:53 PM    File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/spotify.py", line 88, in launch_app
today at 10:53 PM      raise LaunchError(
today at 10:53 PM  pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
```

**Comment by fondberg** [comment]
That is most probably due to it having changed its ipaddress. Try restarting HASS and the device and try again. If it still doesn't work there is little I can do as this seems to fail between pychromecast and the device

**Comment by RafhaanShah** [comment]
It's got a static IP so I don't think that's the issue. Ah well guess it just doesn't like the speaker.

**Comment by fjeddy** [comment]
@fondberg I don't agree with your conclusion here, I had it working perfectly fine, but since it was my first time using Hassio, then I wanted to start over when I got the hang of it. And I did. Started over completely from scratch with a fresh Hassio install and now I can't get this to work anymore.

I used to run the old instance in a KVM using Nebula's Minione Virtualization software. Now I'm just using VirtualBox directly (If it's relevant).

Everything works in terms of PyChromecast and pretty much everything else, except Spotcast. So instantly putting the blame on PyChromecast seems a bit odd considering everything else is working with PyChromecast and the problem seems to solely be with Spotcast and Spotify. "If everything else is working except that one thing, then that one thing is likely the problem".

Care to elaborate why you think this is a PyChromecast issue when it's playing everything else (Local media, radio, youtube etc) perfectly fine? And it's just Spotcast that's having issues.
