### ISSUE TITLE
Failed to set up on Home Assistant Beta

### ISSUE THREAD

**Issue by ZephireNZ** [fondberg/spotcast#172]
After upgrading to Beta, integration is not working. Getting the below error:

```
Setup failed for spotcast: Unable to import component: cannot import name 'KNOWN_CHROMECAST_INFO_KEY' from 'homeassistant.components.cast.media_player' (/usr/src/homeassistant/homeassistant/components/cast/media_player.py)
```

This was removed by PR home-assistant/core#47269

Home Assistant Version: 2021.4.0b0
Spotcast Version: 3.4.7

**Comment by joselito11** [comment]
Have same problem.

**Comment by donkawechico** [comment]
Same

**Comment by RobertD502** [comment]
> Same. And it stops me from being able to restart HA since it doesn't pass the configuration check.
> 
> Had to uninstall to fix it.

Same here. You can comment out spotcast in your configuration.yaml in order to be able to restart without uninstalling. The spotify card associated with spotcast will fail to work as expected, but it'll have to do until an update is pushed to spotcast.

**Comment by raidenlal** [comment]
this key was removed in this commit:
https://github.com/home-assistant/core/commit/3188f796f9deed2310ba372b2e8d0ad35dc1e3ef#diff-48494ab9b042b697108b7d9af51681a431555e9080547201c3c452f051a3aab8

**Comment by user897943** [comment]
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 8:36:53 PM (1 occurrences)
Last logged: 8:36:53 PM

Setup failed for spotcast: Unable to import component: cannot import name 'KNOWN_CHROMECAST_INFO_KEY' from 'homeassistant.components.cast.media_player' (/usr/src/homeassistant/homeassistant/components/cast/media_player.py)

**Comment by hmmbob** [comment]
No need to keep copy pasting the same error without any additional information that hasn't been shared yet.

If you are affected by the same issue, just hit the 👍🏻 button in the first post and hit the subscribe button to receive updates (located at the bottom of the page on mobile views and in the right column on desktops)

**Comment by user897943** [comment]
> No need to reply "same" or keep copy pasting the same error without any additional information that hasn't been shared yet.
> 
> If you are affected by the same issue, just hit the 👍🏻 button in the first post and hit the subscribe button to receive updates (located at the bottom of the page on mobile views and in the right column on desktops)

I already did that.

**Comment by fondberg** [comment]
Hello everybody.

Open source is great and free which in the case of just one person going the work (me) can lead to situations where during periods of sick leave or pressing matters elsewhere (work) thiings piles up.

I would urge you to put efforts into trying to help out by fixing things through pull requests rather than say something is broken several times and come up with arbitrary non version controlled patches.

I too noticed this is broken and if no one chips in i will try and fix it when i have time

**Comment by pipetboy** [comment]
Dear Fondberg,

Some of us may seem ungrateful, but please remember that the large majority of users really appreciate your work. (In fact, the reason people seem ungrateful is because it is such a great integration and everybody misses the functionality).
Personally, I don't have the coding skills to patch it, but I would like to say: Take your time. It will still be there when you get better.

**Comment by icarome** [comment]
I've done a fix up in order to keep working for the time being until someone can do a better job
https://github.com/fondberg/spotcast/pull/173

**Comment by fondberg** [comment]
Fixed together with core PRs. Help me upvote them (links in this PR) https://github.com/fondberg/spotcast/pull/176

**Comment by hmmbob** [comment]
To all users: saying thanks is nice, buying Niklas a coffee is even better. See https://github.com/fondberg/spotcast#donate

**Comment by fondberg** [comment]
Wait with buying coffee until a resolution is in place. Seems the fixes in core are not acceptable

**Comment by fondberg** [comment]
And all, stop upvoting in core. That was my mistake, they don't want that

**Comment by fondberg** [comment]
Fixed in https://github.com/fondberg/spotcast/releases/tag/v3.5.2. Help me test that release.
