### ISSUE TITLE
Spotify doesn't show up on media browser

### ISSUE THREAD

**Issue by prbtt** [fondberg/spotcast#311]
I have both the standard Spotify integration and spotcast installed, but both don't show up on the media tap.
I do have a premium Spotify account. Am I doing something wrong?

**Comment by hmmbob** [comment]
Please use the issue template:

# Bug Ticket

## Describe the bug

A clear and concise description of what the bug is.

* [ ] Using latest version of spotcast
* [ ] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ ] Using latest stable version of Home Assistant
* [ ] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [ ]
 - spotcast version: [ ]

## Configuration

Add your configuration

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context

Add any other context about the problem here.

**Comment by fcusson** [comment]
Hi @prbtt, we haven't heard from you in a week, and we don't have enough information to start helping you. The fact that both integrations won't show up seems to indicate that the problem is first and foremost with the Spotify Integration. I would suggest checking back the [documentation on home assistant](https://www.home-assistant.io/integrations/spotify/) on how to correctly set up Spotify first and after that we could help you.

If possible, provide us with more details. If we haven't heard from you by the end of the week, I'll have to close the issue for inactivity.
