### ISSUE TITLE
Cant valid the config

### ISSUE THREAD

**Issue by MrGlad8** [fondberg/spotcast#318]
Hey! Ok so I added the sp key and sp dc into config as in the manual.
The sp_key however a very long text?

But after save and I try to valid the config it loads forever.. is something wrong?

**Comment by fcusson** [comment]
Hi @MrGlad8. Please use the bug report form. It's very hard to help you without more details:

# Bug Ticket

## Describe the bug

A clear and concise description of what the bug is.

* [ ] Using latest version of spotcast
* [ ] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ ] Using latest stable version of Home Assistant
* [ ] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [ ]
 - spotcast version: [ ]

## Configuration

Add your configuration (anonymize your personal data)

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context

Add any other context about the problem here.

**Comment by fcusson** [comment]
Hi @MrGlad8, please provide more information for us to be able to help you. Otherwise, I'll have to close the ticket for inactivity.

Thank you

**Comment by fcusson** [comment]
closed for inactivity, please reopen if more information is available
