### ISSUE TITLE
Cannot retrieve list of devices

### ISSUE THREAD

**Issue by cavazoshj** [fondberg/spotcast#395]
# Bug Ticket

## Describe the bug

I am unable to retrieve a list of device ID's. Using the Spotify API documentation instructions, I am getting an "invalid username" error. The instructions included in the README do not reflect the existing instructions on the Spotify Doc site as the web api console is no longer there.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [x] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [Container]
 - HA version: [2023.7.2]
 - spotcast version: [3.7.0]

**Comment by fcusson** [comment]
@cavazoshj. This is because you are using the wrong authentication method. The problem is not with Spotcast. You are using the client method, but trying to access a user endpoint. [https://community.spotify.com/t5/Spotify-for-Developers/Invalid-username-cant-get-devices/m-p/5194623#M2447](see ticket in spotify support)

If you want to access user information, you will need oauth 2.0 level tokens. Getting to that endpoint without the web console is much more complex. If you have some knowledge of Python you could use spotipy to get the information.

I'll keep the ticket open to remind we need to update the documentation, but this is mot something that will be fixable quick on my end.

**Comment by Jacksonbm1** [comment]
Hey, you wrote "Getting to that endpoint without the web console is much more complex". I'm confused how you even get to the web console. Could you point us in the right direction?

**Comment by fcusson** [comment]
@Jacksonbm1 simply use [this link](https://developer.spotify.com/documentation/web-api/reference/get-a-users-available-devices). At the time of this ticket the web console was deprecated and favor of a new development platform that spotify was working on. There was a small window when there was no web console available, but this is no longer the case.

**Comment by Jacksonbm1** [comment]
Thank you. I was trying to, but there's a lot more steps it seems that aren't covered in the docs. Is there any chance that will be updated or that you have a resource for me to follow along? For example, it seems to want me to get oauth2, but I can't figure out how to configure that

**Comment by Jacksonbm1** [comment]
Actually, I think I figured it out. I'm going to submit a PR when I get a chance to explain this, but if I don't please feel free to bump me
