### ISSUE TITLE
HA 2024.3.0 Setup failed

### ISSUE THREAD

**Issue by chrismo16** [fondberg/spotcast#434]
Getting this in the logs. Any idea what could be wrong?

Setup failed for custom integration 'spotcast': Unable to import component: cannot import name 'LaunchError' from 'pychromecast.error' (/usr/local/lib/python3.12/site-packages/pychromecast/error.py)

Thanks for the project!

**Comment by fcusson** [comment]
Do you have any more details apart from just the log title.

Also I see you removed the template for bug submission which contains a lot of questions we need to know in order to help you.

I understand you might not be used to submitting bugs on github, but dev usually don't ask questions just for fun, it's because they help us help you. 

Can you please edit your ticket with the bug submission information? We can't help you otherwise here is the link: [bug_report] (https://github.com/fondberg/spotcast/blob/master/.github%2FISSUE_TEMPLATE%2Fbug_report.md)

**Comment by fcusson** [comment]
@chrismo16 actually never mind, this is a duplicate. Closing please follow #433 for more information
