### ISSUE TITLE
Unable to update Spotcast

### ISSUE THREAD

**Issue by Kagey-cmd** [fondberg/spotcast#469]
# Bug Ticket

## Describe the bug

ReadMe suggest HA 2022.2.0 or later is compatible, but most recent update says HA 2024.10 (the current HA release) or older is incompatible. The current version of HA is too old?

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [x ] Using latest version of spotcast
* [ x] Using latest stable version of Home Assistant
* [x ] I have setup the Spotify integration in Home Assistant
* [x ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ x] (optional) I have Spotify Premium
* [x ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: 2024.10.4
 - spotcast version: 3.9.0 (trying to update to 3.9.2 bc Spotcast no longer recognizes any sp-keys).
## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
n/a

````

## Service Call

n/a

````yaml
n/a
````

## Logs

* normal|debug

````log
"This version of Spotcast isn't compatible with Home Assistant 2024.10 or older due to a change in the core library used by the Spotify Integration. v3.9.0 is the newest compatible version for older Home Assistant installation."

## Additional context

<Add any other context about the problem here.>

**Comment by fcusson** [comment]
@DKFrederik Until the release of the `2024.11` I will keep mentioning in the read me that we are targeting `2022.2`, but tomorrow I'm updating that.

`v3.9.2` was released to provide compatbility with the new spotify library in Home Assistant (changed from `spotipy` to `spotifyaio`). This change will break every spotcast version prior to `v3.9.2`. It isn't possible to install `v3.9.2` on the current version of Home Assistant, because `2024.10` doesn't have `spotifyaio`.

The issue you have will not be fixed by updating, as the only change is with the interaction with the Home Assistant Spotify Integration. The cookie management was not touched. If changing the `sp_dc` and `sp_key` for new ones from an incognito or private window doesn't work, we will need more information. Please provide a debug log.

Please edit your ticket to better represent your actual issues and provide logs at the same time

**Comment by fcusson** [comment]
added mention of the version change in read me as warning to help people find the information

**Comment by Kagey-cmd** [comment]
My issue in this case is not "Unable to update sp_dc and sp_key". My issue is the latest Spotcast version is incompatible with the the latest (or any) stable version of Home Assistant.

**Comment by rdenis1** [comment]
This is annoying.  Why are you bombarding us with notifications to update SpotCast when nobody can update SpotCast until 2024.11 is released?  Not cool.

**Comment by Kagey-cmd** [comment]
@fcusson just want to say thanks for maintaining this integration. I know it's time-consuming and mostly thankless.
With that said, I think it's appropriate to open a bug ticket in this case as updates shouldn't be released if they aren't compatible with the latest HA version. Just hold off until the compatible HA is released.

**Comment by fcusson** [comment]
@rdenis1

> Just hold off until the compatible HA is released.

I wish that was so simple, but saddly I maintain this project in my free time and tomorrow is an in office day where I won't have time to make the release.

@rdenis1 

> This is annoying. Why are you bombarding us with notifications to update SpotCast when nobody can update SpotCast until 2024.11 is released? Not cool.

Sorry you find that *not cool*, but the amount of tickets that would get open if the release was not ready at the launch of `2024.11` would be very annoying for me to deal with. I prefer that tomorrow when people make there update they already have access to the release and don't have to wait on me to get back home to fix there home assistant server.

This is not an ideal case, I know. Life doesn't always catters to our personal needs. This is the best case scenario I could take given the circumstances. Sorry for the annoyance, sometimes we just have to accept them.

**Comment by fcusson** [comment]
@lscarneiro v4 is already reserved for an iteration that I'm almost ready to release. Lots of comments already pointing to it.

**Comment by lscarneiro** [comment]
I mean, you're the maintainer, who am I to suggest otherwise, but wouldn't make more sense to just bump said new iteration to like `5.x` and make that fix as `4.x` since it breaks functionality?

My reasoning behind is that nothing prohibits you from having a `120.x` or `99999.x` major release, right? It's not like Google Chrome isn't currently on `130.x`...

Anyway, just suggesting something that would help people understand without reading any notes.

When I see things bumping a major on Home Assistant I jump to the release notes to see what's breaking before pulling the trigger, every time.

**Comment by fcusson** [comment]
@lscarneiro in hindsight I should have done that sure

**Comment by NicoOosterwijk** [comment]
> This is annoying. Why are you bombarding us with notifications to update SpotCast when nobody can update SpotCast until 2024.11 is released? Not cool.

+1

**Comment by fcusson** [comment]
`v3.9.2` was removed due to the high level of annoyance it caused, will be release when I have the time
