### ISSUE TITLE
[b16] Transfer playback does nothing

### ISSUE THREAD

**Issue by rwjack** [fondberg/spotcast#502]
### The problem

When I call the transfer playback action, nothing happens, even when media is currently playing. The play media action works though.

### System Health details

```
System information
Version | core-2024.12.1
-- | --
Spotcast
Version | 5.0.0-b16
-- | --
31pngc6b6ltdrj2yacj3oj6eqrzi Is Default | true
31pngc6b6ltdrj2yacj3oj6eqrzi Public Endpoint | ok
31pngc6b6ltdrj2yacj3oj6eqrzi Public Token | unhealthy
31pngc6b6ltdrj2yacj3oj6eqrzi Private Endpoint | ok
31pngc6b6ltdrj2yacj3oj6eqrzi Private Token | healthy
-- | --
Spotify
Spotify API endpoint reachable | ok
```

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_spotcast_2024-12-11T20-10-53.928Z.log](https://github.com/user-attachments/files/18101630/home-assistant_spotcast_2024-12-11T20-10-53.928Z.log)

**Comment by fcusson** [comment]
@rwjack I'm unable to replicate your issue. The fact that its not working during active playback is even weirder, since you are the only one that reported playback transfer breaking on active playback. All issues were with inactive playback. I will need a bit more information. Please provide the following:

- A copy of the service call you are making
- The type of device you are trying to transfer to
- The type of device that is active at the moment of the attempt
- The type of media you are trying to play (don't need to full uri, but could you provide what is the context like `spotify:album` or `spotify:playlist`

**Comment by fcusson** [comment]
Also, please confirm if you have premium or free. I realised its not yet part of system health info

**Comment by fcusson** [comment]
> don't think Spotcast would have worked without it before.

We're also compatible for free account, but Snapcast doesn't work with free, that's why I asked

**Comment by fcusson** [comment]
so the issue seems to be with using the `start_playback` endpoint with an empty context to a spotify connect device specifically. Its working fine with a smart speaker, but Spotify Connect seem to get confused in these cases.

![{71FDE484-4286-4A43-915D-DE0FB203B092}](https://github.com/user-attachments/assets/e80f465b-f813-4c03-a796-f8ae60ed13df)

I'll test redirecting to the `transfer_playback` endpoint in cases of empty context.

**Comment by fcusson** [comment]
tested using the transfer_playback in spotcast instead of empty context start_playback. Works perfectly for Android Phone, Linux Spotify App and CastAudio Device.

**Comment by fcusson** [comment]
@rwjack released build 17 with a fix for playback transfer. Please reopen if there are any additional issues
