### ISSUE TITLE
[b17] Keep being prompted to reauthenticate

### ISSUE THREAD

**Issue by rwjack** [fondberg/spotcast#504]
### The problem

Happened 3 times in the past 2 days. Initially I thought it was on a 24h interval, but happened this morning as well, 12h after the last login.

### System Health details

```
System information
Version | core-2024.12.1
-- | --
Spotcast
Version | 5.0.0-b17
-- | --
account_id Is Default | true
account_id Public Endpoint | ok
account_id Public Token | healthy
account_id Private Endpoint | ok
account_id Private Token | healthy
account_id Product | premium
-- | --
Spotify
Spotify API endpoint reachable | ok
```

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

don't think it's relevant

**Comment by fcusson** [comment]
@rwjack

> don't think it's relevant

Yes it is, please provide. Need to know what error you got when trying to refresh the token.

Can't work on your ticket unril you.

Ive seen a couple of your ticket. You seem to be afraid of provide too much information (you cut out part of health info, you leave blank info). This does slow down solving issues. Is there anything you are afraid to share, believe might be personal information?

**Comment by fcusson** [comment]
> Yes, I'm trying to provide as little PII as possible

Don't worry I fuuly understand that. I wanted to check more specifically, if there was any PII that I would be logging at the moment that I could look into removing to help on the matter.

**Comment by fcusson** [comment]
You shouldn't have to enable debug, in this case there should be an error log just before I mark the integration's credentials as expired

I have a feeling you have a gateway issue with Spotify and this is going in the token expired error range instead of integration not ready. I would need detail (error code and message) to better understand how I can filter that specific error

**Comment by fcusson** [comment]
Perfect, if you have suggestion, please send them. Glad if we can improve things for everyone

**Comment by fcusson** [comment]
Ok so, like I though this is a gateway issue. I was already planning to filter out 500 errors to go into a wait and retry loop instead of a credential expired state. I'll work on that next. Tis also related to #503. Because, they are linked to the same issue. I'll close this one and continue the work on the first issue. This is just to keep a clean state of the numbers of reported bug, but don't worry, its the next item I'll tackle in the next builds. I'll send a quick build that removes the token expiration on 500 range error, but that will cause all 500 errors to log a traceback. At least the integration will still be working once the gateway is back up. I'll then work on a cleaner way to handle them
