### ISSUE TITLE
Can't update to 2.7.1

### ISSUE THREAD

**Issue by ThirteenTX** [fondberg/spotcast#55]
I just get the error:
"You are running Home Assistant version '0.105.2', but this repository requires minimum version 'null' to be installed."
Tried multiple times.

**Comment by wilfredsmit** [comment]
Upgrade to Home Assistant v0.105.3 and try again. 

Greetings, 

- Wilfred

**Comment by ThirteenTX** [comment]
That worked. I does seem like saying version 105.3 would be less confusing then "null". Either way it works.

**Comment by mixpix405** [comment]
So I'm on 105.3, trying to install Spotcast via HACS for the first time. I'm also getting:

`You are running Home Assistant version '0.105.3', but this repository requires minimum version 'null' to be installed.`

This happens when trying to install the latest version of spotcast (2.7.1) or the 2 other most recent versions (2.7.0 & 2.6.1). I did not go further back to check older versions.

**Comment by fondberg** [comment]
Please upgrade again to avoid diffs in spotipy versions
https://github.com/fondberg/spotcast/releases/tag/v2.7.2
