### ISSUE TITLE
Async executing of spotcast.start

### ISSUE THREAD

**Issue by moejetz** [fondberg/spotcast#63]
The service spotcast.start is executed synchronously. I can confirm that if I call the service and try to switch some entities while the spotcast.start service is still executing. All my switched entities will be executed right after the spotcast.start service has finished, but not meanwhile. By calling e.g. media_player.play_media, this is not the case (my entities are switched directly while the service is still executing).

The problem is, if spotcast.start fails, the service is never finished, causing home assistant to be completely unresponsive, the only solution is to completely restart home assistant. This is very bad as all my lights, automations etc won't work anymore.

I believe this is a new issue, with previous versions of spotcast/home assistant this was not the case. Unfortunately I can't tell you the exact version when this issue raised, but must be in the last 2 or 3 months. Maybe some dependencies have changed...

Related to this comment: https://github.com/fondberg/spotcast/issues/44#issuecomment-587688840

If you need any further information, please let me know :)

**Comment by fondberg** [comment]
There was an issue up to 2.7.1 which could cause a freeze. Can you try with the newest version?

**Comment by moejetz** [comment]
That didn't help unfortunately :(
I'm still experiencing the same issue.

**Log:**
```
2020-02-24 18:34:35 INFO (MainThread) [homeassistant.helpers.script] Script Spotify turn on automation: Executing step call service
2020-02-24 18:34:36 INFO (MainThread) [pychromecast] Querying device status
2020-02-24 18:34:36 ERROR (Thread-7804) [pychromecast.socket_client] [10.10.0.26:42125] Failed to connect, retrying in `5.0s
```

--> System freezes forever. Log won't show any further information.

Spotcast version: 2.8.0
Home Assistant version: 0.105.5

**Comment by fondberg** [comment]
This issue needs to be broken down into 2 parts
1. If pyvhromecast connect fails it locks HA, correct? As the service call is already async it means that HA has an issue here. See https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L203. I can't think of much more I can do.

2. Second issue is that your cast device answers on broadcast but pychromecast can't connect to it. This feels like either a cast device issue or a network issue. Also here there is very little I can think of that i can do in spotcast.

**Comment by soldag** [comment]
I think the main problem is that spotcast pretends to support asyncio, but actually doesn't. Just using the async API doesn't make your code asynchronous. When using the async API, HASS expects the code to be able to suspend itself while waiting for I/O. However, spotipy as well as pychromecast are both blocking, which means that it blocks the whole event loop of HASS while waiting for I/O. 

I guess this issue is caused by the refactoring in https://github.com/fondberg/spotcast/commit/99f42b2e95d62298b457a0ff3bc352c56070e010 and needs to be reverted to use the backwards compatible API that schedules execution in another thread so that it won't block HASS.

**Comment by fondberg** [comment]
I need to look into how HA calls async functions. I would have thought it did it in separate async loops and not the main one. If that is the case I will try and fix that in the main repo.

Back to this issue. What is the proposal exactly @soldag? Reverting back to sync wouldn't solve anything.

**Comment by fondberg** [comment]
After checking more there doesn't seem to be a good implementation of async in HA. It runs all tasks sequentially in one event loop, and it will do an "await" for the current task regardless if it is async or not. This should not deadlock HA though which seems to suggest that pychromecast thread locks could be to blame here.

The core issue here is that HA has cast devices which are not connectable. This needs to be reported because it will make a connect for other non spotcast actions fail too.

If spotcast.start would return immediately and schedule its tasks in an own event loop it would be bad for all the users of spotcast which relies on the return of the service call.

Left is to try and catch this specific connect issue but I as it is pychromecast which locks and don't return it would have to be done in that repo. 
I don't have much time at the moment to dig into this further. 
If you can think of a solution to the problem(s) that could be implemented in spotcast, please write it down as a comment to this issue

**Comment by ASNNetworks** [comment]
I think I have this exact issue since a couple of days. I start a playlist using the service and suddenly nothing works. This happens completely at random. Most of the times the playlist work, but then suddenly it doesn’t and freezes my system. I see the same things in the log as mentioned above. I’m kinda scared to use this server now as my Wake Up Scene and Coming Home Scene. 

One thing I just found out: when I power cycle my internet (my home modem) HA works again after my internet is re-connected. So it’s like HA doesn’t really totally freeze somehow. What I also noticed: transfer_playback doesn’t work as intended anymore. When I actually am playing something it works fine. But then nothing is playing, it won’t fallback to the URI I have in the service. It actually serves the last played song (so still transfers it) BUT it starts the song in a paused state. Perhaps this is related.

**Comment by fondberg** [comment]
Pychronecast will continue trying until it can connect.

Can you open an issue regarding the second issue with transfer playback?

**Comment by ASNNetworks** [comment]
> Pychronecast will continue trying until it can connect.
> 
> Can you open an issue regarding the second issue with transfer playback?

Thanks for your response.

So is this a bug in HA (network), Chromecast integration or spotcast? Or within my own network?

I do have a shit ton of error logs (HomeGraph API) in my log due to Google Home (manual) connection. Could this somehow clog it up? I’m talking about this error: https://community.home-assistant.io/t/request-for-https-homegraph-googleapis-com-v1-devices-reportstateandnotification-failed-403/148289

I will create a separate ticket for the transfer_playback bug.

**Comment by fondberg** [comment]
I would say the issue is with pychromecast not returning with a failure but I will dig a bit deeper and ask how to address this. I might revert to using sync calls if HA deals with failures better there.

**Comment by fondberg** [comment]
Anyone willing to try something which will help the freezing (I think)?
change 
```
        if cast_info:
            return pychromecast._get_chromecast_from_host((
                cast_info.host, cast_info.port, cast_info.uuid,
                cast_info.model_name, cast_info.friendly_name
            ))
```
to 
```
        if cast_info:
            return pychromecast._get_chromecast_from_host((
                cast_info.host, cast_info.port, cast_info.uuid,
                cast_info.model_name, cast_info.friendly_name
            ), tries=2)
```
I haven't tested if the code works but it seems pychromecast will try forever unless one specify retry count

**Comment by ASNNetworks** [comment]
> Anyone willing to try something which will help the freezing (I think)?
> change
> 
> ```
>         if cast_info:
>             return pychromecast._get_chromecast_from_host((
>                 cast_info.host, cast_info.port, cast_info.uuid,
>                 cast_info.model_name, cast_info.friendly_name
>             ))
> ```
> 
> to
> 
> ```
>         if cast_info:
>             return pychromecast._get_chromecast_from_host((
>                 cast_info.host, cast_info.port, cast_info.uuid,
>                 cast_info.model_name, cast_info.friendly_name
>             ), tries=2)
> ```
> 
> I haven't tested if the code works but it seems pychromecast will try forever unless one specify retry count
> 
> this should unfreeze it after 60 seconds tops.

Do I change this in the sensor.py file? If so I can test it and fire multiple calls. I do have to note that I haven’t experienced any freezes anymore. I removed Chromecast component and re-added everything again. I don’t know if that fixed it or I’m just lucky it hasn’t frozen yet.

**Comment by fondberg** [comment]
No, the error has nothing to do with the sensor as I understood it. It showed up when you try to play something using spotcast.start or?

Change here:
https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L249

**Comment by ASNNetworks** [comment]
Allright, I changed the file and restarted HA. I will report back (will try to stress test occasionally when I have time).

**Comment by moejetz** [comment]
I tried the patch but unfortunately it didn't help..

```2020-03-15 17:24:11 INFO (MainThread) [homeassistant.helpers.script] Script Spotify turn on automation: Executing step call service
2020-03-15 17:24:11 INFO (MainThread) [pychromecast] Querying device status
2020-03-15 17:24:14 ERROR (Thread-8593) [pychromecast.socket_client] [10.10.0.25:42125] Failed to connect, retrying in 5.0s
2020-03-15 17:24:14 ERROR (Thread-8593) [pychromecast.socket_client] [10.10.0.25:42125] Failed to connect. No retries.
```

The system still freezes. 

> I would say the issue is with pychromecast not returning with a failure but I will dig a bit deeper and ask how to address this. I might revert to using sync calls if HA deals with failures better there.

I think that would be worth a try since this issue arised with switching to async calls..

**Comment by ASNNetworks** [comment]
Is there a way you can temporary fix this? Or can I revert something to fix this? It freezes at the most unpleasant times (yesterday once and today again) and makes me scared of even using spotcast right now for automations...

**Comment by fondberg** [comment]
I have not had any time for spotcast during the corona outbreak.
As this is open source free of charge it would be great of the community helped out with fixing issues and posting pull requests to make it easier for maintainers.

**Comment by fondberg** [comment]
I also got the original problem. Seems like HA keeps cast devices that are gone from the network and thus can't be connected to. I solved that with rebooting my cast device.

For the hanging I have reverted the async which should result in no more freezes (doesn't solve the connect issue though which is impossible to solve for me)
Try: Fixed in https://github.com/fondberg/spotcast/releases/tag/v2.9.0

**Comment by ASNNetworks** [comment]
> I also got the original problem. Seems like HA keeps cast devices that are gone from the network and thus can't be connected to. I solved that with rebooting my cast device.
> 
> For the hanging I have reverted the async which should result in no more freezes (doesn't solve the connect issue though which is impossible to solve for me)
> Try: Fixed in https://github.com/fondberg/spotcast/releases/tag/v2.9.0

Thanks for all your work! I will update and test it.

**Comment by moejetz** [comment]
@fondberg thank you for all your effort!
Version 2.9.0 fixed the freezing problems for me. Now the spotcast service does not block the rest of home assistant anymore. So now even if spotcast.start fails, everything else remains functional.

So my original intent for this ticket is resolved, thus I will close this ticket.
